// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: notice_service/proto/notice.proto

package notice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_notice_service_proto_notice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notice_service_proto_notice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_notice_service_proto_notice_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type EmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResponse) Reset() {
	*x = EmailResponse{}
	mi := &file_notice_service_proto_notice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResponse) ProtoMessage() {}

func (x *EmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notice_service_proto_notice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResponse.ProtoReflect.Descriptor instead.
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return file_notice_service_proto_notice_proto_rawDescGZIP(), []int{1}
}

func (x *EmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_notice_service_proto_notice_proto protoreflect.FileDescriptor

const file_notice_service_proto_notice_proto_rawDesc = "" +
	"\n" +
	"!notice_service/proto/notice.proto\x12\x06notice\"R\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"'\n" +
	"\rEmailResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2O\n" +
	"\x13NotificationService\x128\n" +
	"\tSendEmail\x12\x14.notice.EmailRequest\x1a\x15.notice.EmailResponseB$Z\"./notice_service/proto/grpc/noticeb\x06proto3"

var (
	file_notice_service_proto_notice_proto_rawDescOnce sync.Once
	file_notice_service_proto_notice_proto_rawDescData []byte
)

func file_notice_service_proto_notice_proto_rawDescGZIP() []byte {
	file_notice_service_proto_notice_proto_rawDescOnce.Do(func() {
		file_notice_service_proto_notice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notice_service_proto_notice_proto_rawDesc), len(file_notice_service_proto_notice_proto_rawDesc)))
	})
	return file_notice_service_proto_notice_proto_rawDescData
}

var file_notice_service_proto_notice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notice_service_proto_notice_proto_goTypes = []any{
	(*EmailRequest)(nil),  // 0: notice.EmailRequest
	(*EmailResponse)(nil), // 1: notice.EmailResponse
}
var file_notice_service_proto_notice_proto_depIdxs = []int32{
	0, // 0: notice.NotificationService.SendEmail:input_type -> notice.EmailRequest
	1, // 1: notice.NotificationService.SendEmail:output_type -> notice.EmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notice_service_proto_notice_proto_init() }
func file_notice_service_proto_notice_proto_init() {
	if File_notice_service_proto_notice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notice_service_proto_notice_proto_rawDesc), len(file_notice_service_proto_notice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notice_service_proto_notice_proto_goTypes,
		DependencyIndexes: file_notice_service_proto_notice_proto_depIdxs,
		MessageInfos:      file_notice_service_proto_notice_proto_msgTypes,
	}.Build()
	File_notice_service_proto_notice_proto = out.File
	file_notice_service_proto_notice_proto_goTypes = nil
	file_notice_service_proto_notice_proto_depIdxs = nil
}
